import { NgModule } from "@angular/core";
//import { CommonModule } from '@angular/common';
import {
  MatDividerModule,
  MatButtonModule,
  MatGridListModule,
  MatRadioModule,
  MatFormFieldModule,
  MatInputModule,
  MatSelectModule,
  MatChipsModule,
  MatSlideToggleModule,
  MatDialogModule,
  MatIconModule,
  MatButtonToggleModule,
  MatTableModule,
  MatAutocompleteModule,
  MatTabsModule,
  MatCheckboxModule,
  MatCardModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTooltipModule,
  MatSliderModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSnackBarModule
} from "@angular/material";

@NgModule({
  imports: [
    MatDividerModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatGridListModule,
    MatRadioModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatChipsModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatIconModule,
    MatButtonToggleModule,
    MatTableModule,
    MatTabsModule,
    MatCheckboxModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    MatSliderModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSnackBarModule
  ],
  exports: [
    MatDividerModule,
    MatButtonModule,
    MatGridListModule,
    MatRadioModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatChipsModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatIconModule,
    MatButtonToggleModule,
    MatTableModule,
    MatAutocompleteModule,
    MatTabsModule,
    MatCheckboxModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    MatSliderModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSnackBarModule
  ]
})
export class MaterialModule {}
